version: '3.8'

services:

  ipfs0:
    image: ipfs/kubo:latest
    container_name: ipfs0
    volumes:
      - ./volumes/ipfs0:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    networks:
      - ipfs-net

  cluster0:
    image: ipfs/ipfs-cluster:latest
    container_name: cluster0
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094
    ports:
      - "9094:9094"
      - "9096:9096"
    volumes:
      - ./volumes/cluster0:/data/ipfs-cluster
    networks:
      - ipfs-net

  ipfs1:
    image: ipfs/kubo:latest
    container_name: ipfs1
    volumes:
      - ./volumes/ipfs1:/data/ipfs
    networks:
      - ipfs-net

  cluster1:
    image: ipfs/ipfs-cluster:latest
    container_name: cluster1
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
    command: daemon --bootstrap /dns4/cluster0/tcp/9096/p2p/12D3KooWFGM2fBgqQsVeZHSegZhxrRqCXjKecPZc8nJBZcz1AF52
    volumes:
      - ./volumes/cluster1:/data/ipfs-cluster
    networks:
      - ipfs-net

  ipfs2:
    image: ipfs/kubo:latest
    container_name: ipfs2
    volumes:
      - ./volumes/ipfs2:/data/ipfs
    networks:
      - ipfs-net

  cluster2:
    image: ipfs/ipfs-cluster:latest
    container_name: cluster2
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: '*'
    command: daemon --bootstrap /dns4/cluster0/tcp/9096/p2p/12D3KooWFGM2fBgqQsVeZHSegZhxrRqCXjKecPZc8nJBZcz1AF52
    volumes:
      - ./volumes/cluster2:/data/ipfs-cluster
    networks:
      - ipfs-net

networks:
  ipfs-net:
    driver: bridge